title: WEMO♥F | Webmontag Offenbach
email: m+wemoof@cto.hiv
description: > # Der Webmontag Offenbach ist eine informelle, nicht-kommerzielle und von der Community organisierte 
  Veranstaltung, die Menschen zusammen bringt, die sich für das Web begeistern, Teil davon sind oder es werden wollen.
baseurl: ""
url: https://wemoof.de
twitter_username: wemoof
twitter_hashtag: wemoof
github_username:  wemoof
author: Markus Tacker
author_url: https://cto.hiv/

# Build settings
markdown: kramdown
