title: WEMO♥F | Webmontag Offenbach
email: markus.tacker+wemoof@gmail.com
description: > # Der Webmontag Offenbach ist eine informelle, nicht-kommerzielle und von der Community organisierte 
  Veranstaltung, die Menschen zusammen bringt, die sich für das Web begeistern, Teil davon sind oder es werden wollen.
baseurl: /www-jekyll
url: http://wemoof.github.io
twitter_username: wemoof
twitter_hashtag: wemoof
github_username:  wemoof
author: Markus Tacker
author_url: https://coderbyheart.com/

# Build settings
markdown: kramdown
